apiVersion: apps/v1
kind: Deployment
metadata:
  name: life-sports-authn-server
  labels:
    app: life-sports-authn-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: life-sports-authn-server
  template:
    metadata:
      labels:
        app: life-sports-authn-server
    spec:
      containers:
      - name: life-sports-authn-server
        image: biuea/life-sports-authn-server
        ports:
          - containerPort: 8100