apiVersion: apps/v1
kind: Deployment
metadata:
  name: life-sports-authn-server
  labels:
    app: authn-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authn-server
  template:
    metadata:
      labels:
        app: authn-server
    spec:
      containers:
        - name: authn-server
          image: biuea/life-sports-authn-server
          ports:
            - containerPort: 8100