apiVersion: v1
kind: Service
metadata:
  labels:
    app: life-sports-authn-server
  name: life-sports-authn-server
  namespace: life-sports
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
    selector:
      app: life-sports-authn-server
    type: NodePort