server:
  port: 8100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://life-sports-discovery-management:8761/eureka

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: life-sports-authn-server
  datasource:
    url: ${MYSQL_URL}
#      jdbc:mysql://mysql:3306/LifeSports?zeroDateTimeBehavior=convertToNull&charset=utf8mb4
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql

jwt:
  key: 1c823csjn11msd56908xzxmcni8u12389090wuasdkljm,zxnc,n,zxncsad22
  access-time: 3600000
  refresh-time: 1209600000